---
abstract: 'Generic navigation in various kinds of trees'
author:
  - 'Laurent Dami, C<< <dami at cpan.org> >>'
  - 'Laurent Dami <dami@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-Navigator
no_index:
  directory:
    - inc
    - t
requires:
  Alien::GvaScript: 0
  DBI: 0
  DBIx::DataModel: 0
  Devel::StackTrace::AsHTML: 0
  Devel::StackTrace::WithLexicals: 0
  Devel::Symdump: 0
  HTTP::Date: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  MooseX::NonMoose: 0
  MooseX::Params::Validate: 0
  Params::Validate: 0
  Plack: 1.0004
  Plack::Component: 0
  Plack::MIME: 0
  Plack::Request: 0
  Plack::Util: 0
  Scalar::Util: 0
  Template: 0
  URI::Escape: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
